### ISSUE TITLE
这个能部署到vercel上面去吗？

### ISSUE THREAD

**Issue by liugod** [wasp-lang/open-saas#11]
这个能部署到vercel上面去吗？

**Comment by infomiho** [comment]
Hey, I've used Google Translate to understand the question to be "Can this be deployed on vercel?"

At the moment the answer is "no" since Wasp's server needs to be constantly running while Vercel so far only supports serverless workloads.

That being said, Wasp apps **can be deployed in many places** like Fly, Railway, Netlify, Heroku etc. we have covered a bunch of them in our docs: https://wasp-lang.dev/docs/advanced/deployment/overview

**Comment by Martinsos** [comment]
Closing issue for now, as it seems to be answered, but feel free to reopen if needed!

**Comment by liugod** [comment]
thank you very much!
