### ISSUE TITLE
Error 401 with authentication "GET /auth/me 401"

### ISSUE THREAD

**Issue by danjeldurmo** [wasp-lang/open-saas#253]
Hello,

After some changes to the layout of login pages, i'm dealing with some warning:

```
[ Server ] GET /auth/me 304
[ Server ] GET /auth/me 401
```

And the layout of login and signup looks suddenly different, maybe for those error.
This isn't blocking login/signup procedure and isn't blocking the entire application but I should investigate what is causing this.

Thanks and best regards,
Danjel Durmo

**Comment by danjeldurmo** [comment]
As per discount community explanation, this behaviour is expected

**Comment by sodic** [comment]
That's correct - this is how Wasp currently checks whether you're logged in or not. It sends a request and looks at the status code.

It's often confusing to users (you're not the only one), which is why we have an open issue to change that: https://github.com/wasp-lang/wasp/issues/1880

I'll link to this issue from that one as extra motivation :)

**Comment by danjeldurmo** [comment]
Thanks you for clarification
