### ISSUE TITLE
Instruct developer to change the project's dir name from `open-saas` to `my-app-name` and to direct it to their own repo

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/open-saas#52]
Let's mention it in the docs somewhere once you clone the repo. The next thing you need to do is change the dir name, and another thing is to change the origin to your own repo. It took me a bit to remember/find out how that is done, so it would be nice to add it to the docs.

**Comment by infomiho** [comment]
I'd suggest we tell users they can fork the repo as well 😊

**Comment by Martinsos** [comment]
This all is handled for you I believe if you pull the `open-saas` via `wasp new`, where you choose `saas`. So maybe that is a better way for users to start open saas project?
Because then we name the folder with the name they provide, there are no issues with wrong origin, ... .

**Comment by GavPierce** [comment]
@Martinsos That is perfect! Thank you, great work Martin.

**Comment by vincanger** [comment]
this is now possible using the `wasp new` command in v0.12, and it's also documented in the case that they use the `github template` option via the repo >> https://docs.opensaas.sh/start/getting-started/#cloning-the-opensaas-template

I'll close this issue for now since this seems to be taken care of from both sides. Feel free to comment on this thread if you have any further questions though.
