### ISSUE TITLE
 Bad CPU type in executable

### ISSUE THREAD

**Issue by swoosh1337** [wasp-lang/open-saas#89]
I am on M1 macbook. Followed the instructions, installed Wasp but when I try to run it it gives me 

`.local/share/wasp-lang/0.13.0/wasp-bin: Bad CPU type in executable`.

Is it something on my end or M1's are not supported? Thanks

**Comment by Martinsos** [comment]
@swoosh1337 please check the "Running Wasp on Mac" on this page: https://wasp-lang.dev/docs/quick-start , it will tell you what to do! Very shortly, Wasp is not directly supported on Mx, so you need to use Rosetta.

@vincanger should we be looking into also adding this info to open-saas installation instructions? Also, would it make sense to have open-saas instructions just take people to wasp's installation instructions, for the part of installing Wasp, since we keep portion missing parts from there to open-saas docs? I know that takes people to out of the docs on the very start though, not sure if that is potentially an issue or not. We could at least to Wasp docs and say "if you need more info / get stuck, check here". That would be improvement for sure, but I do feel we should have a stronger solution.

**Comment by vincanger** [comment]
@Martinsos maybe I can just add the same installation instructions to the open saas docs?

**Comment by vincanger** [comment]
@Martinsos @swoosh1337 i've gone ahead and updated the docs with all the relevant info for installations https://docs.opensaas.sh/start/getting-started/

closing this issue for now :)

**Comment by Martinsos** [comment]
Ok! @vincanger what sucks now a bit is that we have a lot of duplication between this and Wasp docs. Any thoughts on that? One solution is just to link to Wasp docs, how does that sound? Or you think it is better to have it like this?

**Comment by swoosh1337** [comment]
Thanks, guys for the quick response.
